config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'movies/show'
  get 'movies/index'
  resources :lists do
     resources :bookmarks
   end

   resources :movies

   # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  # validates :comment, length: {minimum: 6}, allow_blank: false
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
  has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list_id
  before_action :set_bookmark_id, only: [:edit, :update, :show, :destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
    @bookmark.list_id = @list
    @bookmark.movie_id = @movie.id
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: 422
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark)

  end

  private

    def bookmark_params
      params.require(:bookmark).permit(:comment, :movie_id, :list_id)
    end

    def set_list_id
      @list = List.find(params[:list_id])
    end

    def set_bookmark_id
      @bookmark = Bookmark.find(params[:id])
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # before_action :set_list
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all

  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
    @movies = Movie.all

  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)

    if @list.save
      params[:list][:movie_ids].each do |movie_id|
        next unless movie_id.present?
        Bookmark.create!(movie_id: movie_id.to_i, list: @list)

      end

      redirect_to list_path(@list)

    else
      render :new, status: :unprocessable_entity
    end


  end

  def update

    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :new, status: 422
    end
  end


  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to @list
  end


  private


  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :poster_url)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:edit, :set_movie]
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new

  end

  def create

  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)

    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render :new, status: 422
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to @movie
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :id)
  end

def set_movie
  @movie = Movie.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @movies] do |f| %>
  <%= f.input :name %>
  <%= f.association :movies, :as => :check_boxes %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "The Watch Spot", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Make a List", new_list_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "All Movies", movies_path, class:'nav-link' %>
        </li>

      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Edit a List
          </a>
          <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
            <% @list = List.all  %>
            <%= @list.each do |list|  %>
            <li><%= link_to "#{list.name}", edit_list_path(@list), class: "dropdown-item" %></li>

            <% end %>
            <li><%= link_to "Add a List", new_list_path, class: "dropdown-item" %></li>
            <li><%= link_to "See all Lists", root_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body >
    <header>
      <%= render "layouts/navbar" %>
    </header>
    <div class="container color: #250902">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="bg-light">
<%= simple_form_for (@list) do |f| %>
  <%= f.input :name %>
  <div class="bg-light"><%= f.association :movies, :as => :check_boxes %></div>
  <%= f.submit 'Create list' %>
<% end %>
</div>

app/views/lists/edit.html.erb
  <%= render 'form' %>

app/views/lists/index.html.erb
<div class="row">
  <% @lists.each do |list| %>
  <div class="col-sm-4">
    <div class="card text-bg-light mt-3" style="max-width: 18rem;">

      <h5 class="card-title justify-content-center mx-1"><%= list.name %></h5>
      <div class="card-body mx-1">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
        <%= link_to "#{list.name}", list_path(list), class:"btn btn-warning mx-1 my-1"   %>
    </div>
  </div>
  <% end %>
</div>
<%#= link_to "Make a list", new_list_path %>
  <%# new_list_movies_bookmark %>

app/views/lists/new.html.erb
<h1 class="text-light">Let's set up your new Watch list!</h1>


  <%# <%= form_with model: [@list, @movies] do |f| %>
    <%# <%= f.select :movie, options_for_select(Movie.pluck(:name, :id)), {}, {multiple: true, data: {behavior: 'tom-select'}} %>
    <%# <%= f.submit 'Save', class: "mt-4 btn btn-primary text-white rounded" %>
<%# <% end %>


  <%# <%= simple_form_for [@list, @movies] do |f| %>
    <%# <%= f.association :list, input_html: {} %>
    <%# <%= f.input :movies %>
    <%# <%= f.submit 'Save', class: "btn btn-primary text-white rounded" %>
<%# <% end %>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h1 class="text-light">Here is your list!</h1>
<%# <%= @list.name %>
<%# <%= @list.movies.each do |movie| %>
<%# <h3><%= movie.title %></h3>
<%# <h6><%= movie.overview %></h6>
<%# <h6><%= movie.rating %></h6>
<%# <% end %>
<%# <%= link_to "Back to the main page", lists_path %>
<%# <h3>Edit your list?</h3>
<%= link_to "Edit List",  edit_list_path(@list)%>
<%# <%= link_to "Delete List", @list, data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %> %>


<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title text-justify-center"><%= @list.name %></h5>
  </div>
  <ul class="list-group list-group-flush">
    <% @list.movies.each do |movie| %>
    <li class="list-group-item"><%= movie.title %></li>
    <% end %>
  </ul>
  <div class="card-body">
    <%= link_to "Edit List",  edit_list_path(@list), class:"btn btn-warning" %>
    <%= link_to "Delete List", @list, data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-warning"  %>
  </div>
</div>

app/views/movies/_edit_form.html.erb
<%# <h1 class="text-light">Edit Your movie!</h1>
  <div class="bg-light container">
  #<h3><%= @movie.title %></h3>
  <%# <div class="mb-3"> %>
    <%# <label for="Comments" class="form-label">Comments</label> %>
    <%# <label for="textarea">Write your Overview here:</label> %>
    <%# <textarea class="form-control bg-light" id="exampleFormControlTextarea1" rows="3" placeholder='<%= @movie.overview %>' %>
<%# ></textarea> %>
  <%# </div> %>
  <%# <div class="mx-3">
      <%= link_to "Confirm Changes", movies_path(@movie), class:"btn btn-warning" %>
      <%#= link_to "Go Back", movies_path, class:"btn btn-warning" %>
  <%# </div> %>
<%# </div> %>

<h1 class="text-light">Edit Your movie!</h1>
  <%= simple_form_for @movie do |movie| %>
    <div class="bg-light container">
      <h3><%= @movie.title %></h3>
      <div class="mb-3">
        <%= movie.input :overview, as: :text %>
      </div>
      <%= movie.input :rating, collection: 1..10 %>
      <div class="mx-3">
        <%= movie.submit "Update", class:"btn btn-warning" %>
        <%= link_to "Go Back", movies_path, class:"btn btn-warning" %>
        <%= link_to "Delete Movie", movie_path(movie), class:"btn btn-warning" %>
      </div>
    </div>
<% end %>

app/views/movies/edit.html.erb
<%= render "edit_form" %>

app/views/movies/index.html.erb
  <h1 class="text-light">Movies</h1>
  <%# <div class="movies-grid">
    <% @movies.each do |movie| %>
      <%# <div class="box-poster"> %>
        <%#= link_to movie_path(movie) do %>
          <%#= image_tag movie.poster_url, class: 'img-poster' %>
        <%# end %>
        <%# <p class="movie-path"><%= movie.title</p> %>
      <%# </div> %>
      <%#= link_to "Add a comment", edit_movie_path(movie) %>
    <%# end %>
  <%# </div> %>

<%#
   <% @movies.each do |movie| %>
<%# <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <%# <h5 class="card-title"><%= movie.title %>
        <%# <p class="card-text"><%= movie.comment %>
        <%# <div class="d-flex justify-content-evenly">
          <p class="card-text"><%= link_to "Add a comment", edit_movie_path(movie), class:"btn btn-warning" %></p>
          <%# <p class="card-text"><%= link_to "Add a bookmark", edit_movie_path(movie), class:"btn btn-warning" %></p> %>
        <%# </div>
      </div>
    </div>
  </div>
</div> %>
<%# end %>


<div class="row">
    <% @movies.each do |movie| %>
      <div class="col-sm-4">
        <div class="card text-bg-light mt-4" style="max-width: 20rem;">
        <i class="fa-solid fa-star position-absolute top-0 end-0"><%= movie.rating %></i>
            <%# <div class="position-absolute top-0 end-0"><%= movie.rating %>
          <h5 class="card-title justify-content-center"><%= movie.title %></h5>
            <div class="card-body">
              <p class="card-text"><%= movie.overview %></p>
            </div>
            <div class="d-flex justify-content-sm-evenly mx-1">
              <p class="card-text"><%= link_to "Edit overview", edit_movie_path(movie), class:"btn btn-warning" %></p>
              <p class="card-text"><%= link_to "View movie", movie_path(movie), class:"btn btn-warning" %></p>
            </div>
        </div>
      </div>
<% end %>
</div>

app/views/movies/show.html.erb
<div class="container mt-15-px">
  <div class="row movie-display ">
    <div class="col-md-6 float-md-end mb-3 ms-md-3">
      <img class="img-poster img-fluid" src="<%= @movie.poster_url %>" >
    </div>
    <div class="position-absolute top-50 start-100 translate-middle mx-5">
      <div class="col-md-6 bg-light">
        <div>
          <h3><%= @movie.title %></h3>
          <i class="fa-solid fa-star"><%= @movie.rating %></i>
        </div>

        <div>
        <h5>Overview</h5>
          <em><p><%= @movie.overview %></p></em>
        </div>
        <div class="justify-content-center mx-1">
          <%= link_to "Go Back", movies_path, class:"btn btn-warning" %>
          <%= link_to "Edit overview", edit_movie_path(@movie), class:"btn btn-warning" %>
          <%= link_to "Delete Movie", @movie, data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-warning"  %>
        </div>
      </div>
    </div>
  </div>
</div>